### ISSUE TITLE
Group profiles: slight design adjustements

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#140]
@Richenda said [here](https://github.com/rtcharity/hubreboot/issues/137): 
> I'm a bit confused by the change to what the group profile page looks like design wise. There used to be a purple block for 'key facts' now it's mostly white and the other grey blocks have been whited? Is this temporary or a bug or something?

**Comment by sebgrebe** [comment]
[Done](https://github.com/rtcharity/hubreboot/commit/7b40fa48efd2324548169f9dd2aebac79e7163d8)

**Comment by Richenda** [comment]
Sorry to reopen. This isn't a deal breaker but the current style of the key facts block still isn't 100% sitting right. I don't want to throw the baby out with the bathwater. I'm guessing you guys changed it because of reasons. Perhaps you could tell me what they were? I'm guessing lines were added because it seemed as though it was hard for a reader to follow the right line of text without distinguishing rows? I can empathise with that. Although the downside is that now the block looks a bit to me like the kind of paper we write in at school if you know what I mean? Also I do still think that the text is much nicer white than black if that's an option.

For the purple, I think this faded purple is ok. I'm not so cool with the darker purple horizontal lines. Is there a way we can change those? I'm thinking we could do a slightly different approach like the table I'm adding below OR we could make those lines white or pale grey. I don't want to hold back launch over this, but it is bugging me. What do you think? @sebgrebe 
<img width="353" alt="screenshot 2019-01-29 at 14 46 18" src="https://user-images.githubusercontent.com/14843012/51945860-adf40480-23d4-11e9-8000-856bb0c539fc.png">


<img width="428" alt="screenshot 2019-01-29 at 14 22 53" src="https://user-images.githubusercontent.com/14843012/51945281-1c37c780-23d3-11e9-9588-67b714cc3611.png">

**Comment by Richenda** [comment]
We could ask the group also

**Comment by Richenda** [comment]
I mean the Hubreboot team

**Comment by sebgrebe** [comment]
@Richenda  Done.

**Comment by Richenda** [comment]
@sebgrebe thanks. I think it looks great. I hope you're also happy?

**Comment by sebgrebe** [comment]
@Richenda yep :)
